const newReviews = [
	{
		rating: 3,
		comment: "satisfactory",
	},
	{
		rating: 5,
		comment: "Good quality product",
	},
]

const newProducts = [
	{
		name: "addie",
		image: "/images/addie.jpg",
		price: 50,
		discount: 35,
		category: "shoes",
		gender: "male",
		countInStock: 13,
		description: "Comfortable shoes for men",
	},
	{
		name: "aiter-blue",
		image: "/images/aiter-blue.jpg",
		price: 150,
		category: "shirts",
		gender: "male",
		countInStock: 3,
		description: "Comfortable shirt for fashion men",
	},
	{
		name: "bison",
		image: "/images/bison.jpeg",
		price: 50,
		category: "accessories",
		gender: "male",
		countInStock: 5,
		description: "Mens glasses",
	},
	{
		name: "black-chinos",
		image: "/images/black-chinos.jpeg",
		price: 130,
		discount: 100,
		category: "trousers",
		gender: "male",
		countInStock: 4,
		description: "trousers shoes for men",
	},
	{
		name: "blue-jean",
		image: "/images/blue-jean.jpeg",
		price: 150,
		category: "trousers",
		gender: "female",
		countInStock: 13,
		description: "Great jeans that shows the woman in you",
	},
	{
		name: "cindy-gown",
		image: "/images/cindy-gown.jpeg",
		price: 500,
		discount: 400,
		category: "dresses",
		gender: "female",
		countInStock: 13,
		description: "Great dress for outdoor events",
	},
	{
		name: "curren",
		image: "/images/curren.jpeg",
		price: 110,
		category: "shoes",
		gender: "male",
		countInStock: 13,
		description: "Comfortable shoes for men",
	},
	{
		name: "dorian",
		image: "/images/dorian.jpeg",
		price: 250,
		category: "accessories",
		gender: "female",
		countInStock: 4,
		description: "Nice women bags",
	},
	{
		name: "flace",
		image: "/images/flace.jpeg",
		price: 80,
		discount: 50,
		category: "skirts",
		gender: "female",
		countInStock: 13,
		description: "Good top, fits every top",
	},
	{
		name: "flora",
		image: "/images/flora.jpeg",
		price: 60,
		category: "tops",
		gender: "female",
		countInStock: 1,
		description: "Comfortable shoes for women",
	},
	{
		name: "guccci watch",
		image: "/images/guccci.jpg",
		price: 70,
		discount: 50,
		category: "accessories",
		gender: "female",
		countInStock: 0,
		description: "Nice women fashion",
	},
	{
		name: "gucci glass",
		image: "/images/gucci-women.jpeg",
		price: 50,
		category: "accessories",
		gender: "female",
		countInStock: 5,
		description: "Wonderful women glasses",
	},
]

export { newProducts, newReviews }
